[build]
  base = "frontend"  # The directory where Netlify will look for the build command
  publish = "frontend/build"  # The directory where the built files are located
  command = "npm run build"  # The command to build your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200